### ISSUE TITLE
启动茶绘君出现“对不起，服务器貌似断开了。”的错误提示

### ISSUE THREAD

**Issue by uboa3774** [liuyanghejerry/painttyWidget#73]
**Env**
- [x] Windows 7

**Version**
- [x] 0.54

**Reproduce step**
1. 双击启动茶绘君
2. 检查文件夹生成的log文件

**Note**

以下是log信息……请问是阿里云服务到期了吗；；？
2018/07/28 00:21:00 Post http://update.mrspaint.com:17979: dial tcp 115.29.229.23:17979: ConnectEx tcp: No connection could be made because the target machine actively refused it.
2018/07/28 00:21:00 error when post
2018/07/28 00:21:00 check failed
2018/07/28 00:21:00 Post http://update.mrspaint.com:17979: dial tcp 115.29.229.23:17979: ConnectEx tcp: No connection could be made because the target machine actively refused it.

**Comment by liuyanghejerry** [comment]
木有，只是关掉了更新通道。服务断开主要是由于主服务BUG导致的，和log里的更新服务没啥关系。已重启主服务，现在应该能用了。
